# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171208_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_userinfo_date',
            name='date',
            field=models.CharField(max_length=32, verbose_name='日期'),
        ),
    ]
